name: refy


on: push
#  schedule:
#    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          
      - name: execute py script # run the run.py to get the latest data
        run: |
          python update.py
