name: refy


#on: push
#  schedule:
#    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
#on:
#  push:
#    branches:
#    - main
#  schedule:
#  -cron: "0 8 * * 1" # Every Monday at 9AM UK time (8 AM UTC)
on:
  schedule:
  - cron: "0 11 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/FedeClaudi/refy.git
          
      - name: execute py script # run the run.py to get the latest data
        run: |
          python scripts/run_refy.py
