name: test


on: push

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Commit refy.html
        run: |
          git config --global user.name 'auto-update'
          git config --global user.email 'FedeClaudi@users.noreply.github.com'
          git commit -am "updating refs"
          git push
